version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test --ci --runInBand
      - store_artifacts:
          path: test-reports
          destination: test-reports
      - store_test_results:
          path: test-reports
